# XGBoost for Whale Classification

In this assignment, you have been provided a dataset that consists of echo-location clicks of two types of whales, namely, Gervais and Cuviers. Your task is to classify the different types whales using Gradient Boosting with the help of the XGBoost library. You are expected to fill in functions that would complete this task. We use XGBoost here instead of GradientBoostedTrees in Spark because XGBoost running on a single machine is much faster than Spark running on 10 machines.

The data files were preprocessed on PySpark (10 nodes) cluster. The code for the same can be found in Data_Processing_Whales.ipynb. The preprocessed data is a numpy array with `4175` rows (for the 10mb file) with following columns (zero-indexed):
* Col 0-9: projections on first 10 eigen vectors
* Col 10: rmse
* Col 11: peak2peak
* Col 12: label (`0 if row.species==u'Gervais' else 1`)

You can also refer to XGBoost_Whales.ipynb under for more details on the XGBoost Analysis before you attempt this assignment.

Both Data_Processing_Whales.ipynb and XGBoost_Whales.ipynb can be found under Lecture Notebooks Spring 2023/Section3-Classification/XGBoost directory in Vocareum.

## XGBoost - Theory

A brief overview of gradient boosting in XGBoost can be found here:

* https://xgboost.readthedocs.io/en/latest/tutorials/model.html
* https://xgboost.readthedocs.io/en/latest/python/python_intro.html

Use the XGBoost API for training and predicting scores: 

* http://xgboost.readthedocs.io/en/latest/python/python_api.html

#### Main API

* `xgboost.train` is the learning API that trains the Gradient Boosting Model,
   * The main parameters are:
      * **plst** – XGBoost parameter list
      * **dtrain** – Data to be trained
      * **num_round** – Number of iterations of boosting. (default: 100)
      * **evallist** – List of items to be evaluated during training
      * **verbose_eval** - This can be used to control how much information the train function prints. You might want to set to **False** to avoid printing logs.
* `bst.predict` is the API that makes score predictions
   * The main parameters are:
      * **dtest** – Test Data
      * **dtrain** – Data to be trained
      * **ntree_limit** – Limit number of trees in the prediction (Use: ntree_limit=bst.best_ntree_limit)
      * **output_margin** - Whether to output the raw untransformed margin value (Use: output_margin=True)

## Notebook Setup

### Importing Required Libraries

In [1]:
%matplotlib inline
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import pickle
import random

In [2]:
xgb.__version__

'0.72'

### Loading Data

In [3]:
with open('./resource/asnlib/publicdata/X_train.pkl', 'rb') as f:
    X_train = pickle.load(f)

with open('./resource/asnlib/publicdata/X_test.pkl', 'rb') as f:
    X_test = pickle.load(f)

with open('./resource/asnlib/publicdata/y_train.pkl', 'rb') as f:
    y_train = pickle.load(f)

with open('./resource/asnlib/publicdata/y_test.pkl', 'rb') as f:
    y_test = pickle.load(f)

### Setting Parameters for XG Boost
* Maximum Depth of the Tree = 3 _(maximum depth of each decision trees)_
* Step size shrinkage used in update to prevents overfitting = 0.3 _(how to weigh trees in subsequent iterations)_
* Evaluation Criterion= Maximize Loglikelihood according to the logistic regression _(logitboost)_
* Maximum Number of Iterations = 1000 _(total number trees for boosting)_
* Early Stop if score on Validation does not improve for 5 iterations

[Full description of options](https://xgboost.readthedocs.io/en/latest/parameter.html)

In [4]:
#You can change this cell if you wish to, but you aren't expected to
def xgboost_plst():
    param = {}
    param['max_depth']= 3   # depth of tree
    param['eta'] = 0.3      # shrinkage parameter
    param['silent'] = 1     # not silent
    param['objective'] = 'binary:logistic'
    param['nthread'] = 7 # Number of threads used
    param['eval_metric'] = 'logloss'

    plst = param.items()
    return plst

## Exercises

### Computing the score ranges

The function `calc_stats` takes the xgboost margin scores as input and returns two numpy arrays `min_scr`, `max_scr` which are calculated as follows:

1. `min_scr`: mean - (3 $\times$ std)
2. `max_scr`: mean + (3 $\times$ std)

Here the input margin scores, represents the processed XGBoost margin scores obtained from the `bootstrap_pred` function. Each row represents the various scores for a specific example in an iteration and your `calc_stats` function is supposed to compute the `min_scr` and `max_scr` as defined for each example. So in the example below, we take a scenario where we have 3 examples which have 4 values each (From 4 bootstrap iterations).

#### Tasks:

Finish the function `calc_stats`.

Input:

- `margin_scores`: a 2d numpy array that contains xgboost margin scores. 

Output: 

- 2 numpy arrays of `min_scr` and `max_scr` as defined above. 


**Note**: Ensure you round the values in the numpy arrays to two decimal places

---

**<font color="magenta" size=2>Example Input</font>**
``` python
[[-0.22 -0.19 -0.17 -0.13][-0.1 -0.05 0.02 0.10][0.03 0.11 0.12 0.15]]
```


**<font color="blue" size=2>Example Output</font>**
``` python
(array([-0.28 -0.23 -0.03]),
 array([-0.08  0.22  0.24]))
```

In [5]:
margin_score = np.array([[-0.22, -0.19, -0.17, -0.13], [-0.1, -0.05, 0.02, 0.10], [0.03, 0.11, 0.12, 0.15]])
margin_score

array([[-0.22, -0.19, -0.17, -0.13],
       [-0.1 , -0.05,  0.02,  0.1 ],
       [ 0.03,  0.11,  0.12,  0.15]])

In [6]:
mean_cols = np.mean(margin_score, axis=1)
std_cols = np.std(margin_score, axis=1)
out_low = mean_cols - 3*std_cols
out_high = mean_cols + 3*std_cols
out_low = np.round(out_low, decimals=2)
out_high = np.round(out_high, decimals=2)
out_high
#out_low

array([-0.08,  0.22,  0.24])

In [7]:
margin_score = np.array([[-0.22, -0.19, -0.17, -0.13], [-0.1, -0.05, 0.02, 0.10], [0.03, 0.11, 0.12, 0.15]])
min_score, max_score = calc_stats(margin_score)
assert type(min_score) == np.ndarray, 'Incorrect Return type'
assert type(max_score) == np.ndarray, 'Incorrect Return type'

NameError: name 'calc_stats' is not defined

In [118]:
margin_score

array([[-0.22, -0.19, -0.17, -0.13],
       [-0.1 , -0.05,  0.02,  0.1 ],
       [ 0.03,  0.11,  0.12,  0.15]])

In [119]:
test_trans = margin_score.T

In [8]:
calc_stats(margin_score)

NameError: name 'calc_stats' is not defined

In [24]:
testing = np.array([[-0.22, -0.19, -0.17, -0.13, -0.18, -0.22, -0.19, -0.17], [-0.1, -0.05, 0.02, 0.10, -0.1, -0.05, 0.02, 0.10], [0.03, 0.11, 0.12, 0.15, 0.03, 0.11, 0.12, 0.15]])
test_min_score, test_max_score = calc_stats(testing)

In [25]:
test_min_score

array([-0.28, -0.23, -0.03])

In [23]:
testing = np.array([[-0.22, -0.19, -0.17, -0.13, -0.18, -0.22, -0.19, -0.17], [-0.1, -0.05, 0.02, 0.10, -0.1, -0.05, 0.02, 0.10], [0.03, 0.11, 0.12, 0.15, 0.03, 0.11, 0.12, 0.15]])

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [5]:
def calc_stats(margin_scores):
    ###
    ### YOUR CODE HERE
    ###
    mean_cols = np.mean(margin_scores, axis=1)
    std_cols = np.std(margin_scores, axis=1)
    min_scr = mean_cols - 3*std_cols
    max_scr = mean_cols + 3*std_cols
    
    min_scr = np.round(min_scr, decimals=2)
    max_scr = np.round(max_scr, decimals=2)
    
    return min_scr, max_scr
    

In [48]:
calc_stats(test_trans)

NameError: name 'test_trans' is not defined

In [6]:
margin_score = np.array([[-0.22, -0.19, -0.17, -0.13], [-0.1, -0.05, 0.02, 0.10], [0.03, 0.11, 0.12, 0.15]])
min_score, max_score = calc_stats(margin_score)
assert type(min_score) == np.ndarray, 'Incorrect Return type'
assert type(max_score) == np.ndarray, 'Incorrect Return type'

In [7]:
assert (min_score == np.array([-0.28, -0.23, -0.03])).all(), "Incorrect return value"

In [8]:
assert (max_score == np.array([-0.08,  0.22,  0.24])).all(), "Incorrect return value"

In [9]:
# Hidden Tests Here
###
### AUTOGRADER TEST - DO NOT REMOVE
###


In [10]:
# Hidden Tests Here
###
### AUTOGRADER TEST - DO NOT REMOVE
###


### Calculating predictions

Based on the ranges for each of the examples, i.e, (`min_scr`, `max_scr`), we can predict whether it's a Gervais or a Cuvier. Since all our scores will be between -1 and +1, we use 0 as the margin line. All examples which are on the left side of the margin, can be classified as Cuvier's and all which are on the right side can be classified as Gervais. However, since we take margin scores from a set of bootstraps for each example, we use the minimum and maximum score arrays to predict to determine the classification.

#### Tasks:

Finish the function `predict`, which takes the minimum score array and maximum score array and returns predictions as follows:

1. If respective minimum score and maximum score values are less than 0, predict -1 (**Cuvier's**)
2. If respective minimum score value is less than 0 and maximum score value is greater than 0, predict 0 (**Unsure**)
3. If respective minimum score and maximum score values are greater than 0, predict 1 (**Gervais**)


Input:

- `min_scr`: the numpy array from `calc_stats`

- `max_scr`: the numpy array from `calc_stats`

Output: 

- a numpy array of predictions

---

**<font color="magenta" size=2>Example Input</font>**
``` python
min_scr (numpy array) = [-0.78 -0.68 -0.6 -0.53 -0.47 -0.42 -0.32 -0.21 -0.07 0.22]

max_scr (numpy array) = [-0.49 -0.39 -0.33 -0.25 -0.2 -0.11 -0.04 0.1 0.3 0.51]
```

**<font color="blue" size=2>Example Output</font>**
``` python
[-1 -1 -1 -1 -1 -1 -1  0  0  1]
```

In [11]:
max_s = np.array([-0.49, -0.39, -0.33, -0.25, -0.2, -0.11, -0.04, 0.1, 0.3, 0.51])
min_s = np.array([-0.78, -0.68, -0.6, -0.53, -0.47, -0.42, -0.32, -0.21, -0.07, 0.22])

#true_pred = np.array([-1, -1, -1, -1, -1, -1, -1, 0, 0, 1])

In [12]:
class1 = np.zeros_like(max_s, dtype=int)
class1[(max_s < 0) & (min_s < 0)] = -1
class1[(max_s > 0) & (min_s < 0)] = 0
class1[(max_s < 0) & (min_s > 0)] = 0
class1[(max_s > 0) & (min_s > 0)] = 1
class1

array([-1, -1, -1, -1, -1, -1, -1,  0,  0,  1])

In [53]:
def predict(min_scr, max_scr):
    ###
    ### YOUR CODE HERE
    ###
    class1 = np.zeros_like(max_s, dtype=int)
    class1[(max_s < 0) & (min_s < 0)] = -1
    class1[(max_s > 0) & (min_s < 0)] = 0
    class1[(max_s < 0) & (min_s > 0)] = 0
    class1[(max_s > 0) & (min_s > 0)] = 1
    return class1

In [11]:
# Option B

def predict(min_scr, max_scr):
    ###
    ### YOUR CODE HERE
    ###
    # We set up a for loop here with if, elif, else statements to assign predictions
    pred = np.zeros((len(min_scr)), np.int)
    for i in range(len(min_scr)):
        if max_scr[i] < 0:
            pred[i] = -1
        elif min_scr[i] * max_scr[i] <= 0:
            pred[i] = 0
        else:
            pred[i] = 1
    return pred

In [12]:
max_s = np.array([-0.49, -0.39, -0.33, -0.25, -0.2, -0.11, -0.04, 0.1, 0.3, 0.51])
min_s = np.array([-0.78, -0.68, -0.6, -0.53, -0.47, -0.42, -0.32, -0.21, -0.07, 0.22])
pred = predict(min_s, max_s)
true_pred = np.array([-1, -1, -1, -1, -1, -1, -1, 0, 0, 1])

In [13]:
print(pred)

[-1 -1 -1 -1 -1 -1 -1  0  0  1]


In [14]:
assert type(pred) == np.ndarray, 'Incorrect return type'

In [15]:
assert (pred == true_pred).all(), 'Incorrect return value'

### Calculating scores

You can follow these procedures to train a number of XGBoost models using bootstrap and test their performances.

Repeat the given procedure for `n_bootstrap` number of iterations:

For `n_bootstrap` iterations:
* Sample `boostrap_size` indices from the training set **with replacmennt**.
* Create train and test data matrices `(dtrain, dtest)` using `xgb.DMatrix(X_sample, label=y_sample)`.
* Initialise the `evallist` parameter `[(dtrain, 'train'), (dtest, 'eval')]`.
* Train the model using the XGBoost train API and make score predictions using bst.predict object returned by XGB train API. **Ensure you set `output_margin=True` to get raw untransformed output scores and `ntree_limit=bst.best_ntree_limit`**.
* Normalize them by dividing them with the normalizing factor as `max(scores) - min(scores)` and round these values to a precision of two decimal places.

Then: 
* For each individual example, remove scores below the minRth score and greater than the maxRth score(sort for each example if necessary).
* Call the `calc_stats` function to compute `min_scr` and `max_scr` with the filtered margin scores as parameter.
* Return the `min_scr` and `max_scr` computed by the `calc_stat` function using the margin scores.

#### Task:

Finish the function `bootstrap_pred`.

Input:

- `Training set`: the training set.
- `Test set`: the test test.
- `n_bootstrap`: number of bootstrap samples that run XGBoost and trains one part of the sample set.
- `minR, maxR`: two numbers such that $0 < minR < maxR < 1$ that define the fractions of the `n_bootstrap` scores that define the range.
- `bootstrap_size`: number of bootstrap samples on which you will run XGBoost.
- `num_round`: number of iterations for running xgboost.
- `plst`: parameter List.

Output:

- The output should be a confidence interval for each example in the test set (`min_scr` and `max_scr`). 

**Note**: 

- Please see the [Main API](#Main-API) section above to see how to use XGBoost.
- Remember to set `num_round` and `plst` as specified by the parameters in `xgb.train`.
- You can experiment by changing `n_bootstraps`, but it takes about 200 iterations to get consistent values.

In [40]:
xgboost_plst()

dict_items([('max_depth', 3), ('eta', 0.3), ('silent', 1), ('objective', 'binary:logistic'), ('nthread', 7), ('eval_metric', 'logloss')])

In [41]:
n_bootstrap

NameError: name 'n_bootstrap' is not defined

In [42]:
index = np.random.choice(10)
index

2

In [32]:
def bootstrap_pred(X_train, X_test, y_train, y_test, n_bootstrap, minR, maxR, bootstrap_size, \
                   num_round=100, plst=xgboost_plst()):
    # Setting some initial variables, one the size of the length of the training set and an empty list for our scores
    ts = len(X_train)
    scores = []
    
    # Here we will need to loop through every item from n_boostrap, which here is 100
    for i in range(n_bootstrap):
        # Randomly choosing numbers to include as samples
        sample_indices = np.random.choice(ts, bootstrap_size)
        
        # breaking out x and y sample sets based on X_train and y_train inputs
        X_samp = X_train[sample_indices]
        y_samp = y_train[sample_indices]
        
        # creating dtrain and dtest as outlined in the directions
        dtrain = xgb.DMatrix(X_samp, label=y_samp)
        dtest = xgb.DMatrix(X_test, label=y_test)
        
        # do the actual training using the boosting algorithm.
        # we have parameters set using plst, we set up dtrain above using the xgb.DMatrix, num_round=100
        top = xgb.train(plst, dtrain, num_round)
        
        # creating our score variable using top we set above and predicting on the dtest.
        # implementing output_margin=True as explained above
        score = top.predict(dtest, output_margin=True)
        
        # Normalizing score using the range
        score /= np.max(score) - np.min(score)
        
        # Two decimal places as instructed
        score = np.around(score, 2)
        
        # Sorting by creating a minimum and maxiumum threshold using minR and maxR
        thresh_min = np.percentile(score, minR)
        thresh_max = np.percentile(score, maxR)
        
        # Limiting the values in my array using my threshold min and max
        margin_score = np.clip(score, thresh_min, thresh_max)
        
        
        # Adding to scores
        scores.append(score)
    
    # Making scores an array
    scores = np.asarray(scores)
    
    # Utilizing calc_stats to return the min_scr and max_scr
    min_score, max_score = calc_stats(scores.T)
    
    return min_score, max_score

In [17]:
scores

NameError: name 'scores' is not defined

In [33]:
def process(X_train, X_test, y_train, y_test, n_bootstrap=100):
    min_scr, max_scr = bootstrap_pred(X_train, X_test, y_train, y_test, n_bootstrap=n_bootstrap, \
                                            minR=0.1, maxR=0.9, bootstrap_size=len(X_train))
    pred = predict(min_scr, max_scr)
    return min_scr, max_scr, pred

#### Tests

How we test the function:
1. We have computed the average mid-point of the range of values and verify that this midpoint is present in the range computed by your function
2. We check that the length of the `interval(max_scr-min_scr)` is not more than twice the average length of the interval

In [34]:
sample_indices = np.load('./resource/asnlib/publicdata/vis_indices.npy')
X_test_samp = X_test[sample_indices]
y_test_samp = np.array(y_test[sample_indices], dtype=int)
midpt = np.load('./resource/asnlib/publicdata/vis_midpt.npy')
avg_length = np.load('./resource/asnlib/publicdata/vis_avg_length.npy')
min_scr, max_scr, pred = process(X_train, X_test_samp, y_train, y_test_samp)
length = max_scr - min_scr

In [35]:
sample_indices

array([ 434, 1069,  967, 1069,  606, 1195,    2,  544,  981, 1021])

In [36]:
X_test_samp

array([[ 179.15523187,   12.21272216,   74.46259312,    7.60822746,
         -38.39473352,    2.82498963,   -1.92510683,  -56.06387065,
          26.62025097,   59.63988288,   12.1305567 ,   52.7755    ],
       [ 116.13874678,  -51.78060175,   92.0938067 ,  -10.30169229,
         -90.04445841,   10.32201965,   -6.40444673,  -57.57118102,
           7.60560986,   48.92373612,   14.63210427,   58.049     ],
       [ 191.57689457,  -62.09868097,   89.22060215,  -35.37121627,
         -62.45716715,   28.54705146,    1.8575916 ,  -45.53066025,
           7.52909133,   38.39328859,   11.46367576,   50.0524    ],
       [ 116.13874678,  -51.78060175,   92.0938067 ,  -10.30169229,
         -90.04445841,   10.32201965,   -6.40444673,  -57.57118102,
           7.60560986,   48.92373612,   14.63210427,   58.049     ],
       [ 295.14936595,   -9.87612027,  169.72992738,  -10.042956  ,
         -63.66228591,   21.20951729,  -20.47992607,  -38.77776627,
           9.81148741,   44.26095182,   14.7

In [63]:
y_test_samp

array([1, 0, 1, 0, 0, 1, 1, 0, 1, 0])

In [64]:
min_scr

array([-0.24, -0.59, -0.58, -0.59, -0.29,  0.16,  0.03, -0.68,  0.29,
       -0.22], dtype=float32)

In [65]:
max_scr

array([ 0.21, -0.15,  0.  , -0.15,  0.27,  0.63,  0.39, -0.4 ,  0.59,
        0.38], dtype=float32)

In [66]:
midpt

array([-0.02, -0.34, -0.3 , -0.34, -0.01,  0.39,  0.19, -0.52,  0.44,
        0.06], dtype=float32)

In [37]:
sum(min_scr <= midpt)

10

In [38]:
sum(max_scr >= midpt)

10

In [39]:
(0.7 * len(sample_indices))

7.0

In [40]:
assert sum(min_scr <= midpt) >= (0.7 * len(sample_indices)), "Incorrect range (mean - 3*std) to (mean + 3*std)"

In [41]:
assert sum(max_scr >= midpt) >= (0.7 * len(sample_indices)), "Incorrect range (mean - 3*std) to (mean + 3*std)"

In [42]:
assert sum(length < 2*avg_length) >= (0.7 * len(sample_indices)), "Incorrect length of range (mean - 3*std) to (mean + 3*std)"

In [43]:
length

array([0.44      , 0.45      , 0.59000003, 0.45      , 0.45      ,
       0.48      , 0.35      , 0.31      , 0.31000003, 0.49      ],
      dtype=float32)

In [33]:
avg_length

array([0.29, 0.3 , 0.34, 0.3 , 0.33, 0.33, 0.23, 0.21, 0.21, 0.39],
      dtype=float32)

In [43]:
sample_indices

array([ 434, 1069,  967, 1069,  606, 1195,    2,  544,  981, 1021])

In [42]:
sum(length < 2*avg_length[sample_indices])

IndexError: index 434 is out of bounds for axis 0 with size 10

In [37]:
(0.7 * len(indices2))

NameError: name 'indices2' is not defined

In [44]:
# Hidden Tests Here
###
### AUTOGRADER TEST - DO NOT REMOVE
###


In [45]:
# Hidden Tests Here
###
### AUTOGRADER TEST - DO NOT REMOVE
###


In [46]:
# Hidden Tests Here
###
### AUTOGRADER TEST - DO NOT REMOVE
###


In [47]:
# Hidden Tests Here
###
### AUTOGRADER TEST - DO NOT REMOVE
###


In [48]:
# Hidden Tests here
###
### AUTOGRADER TEST - DO NOT REMOVE
###


In [49]:
# Hidden Tests here
###
### AUTOGRADER TEST - DO NOT REMOVE
###


In [50]:
# Hidden Tests here
###
### AUTOGRADER TEST - DO NOT REMOVE
###


In [51]:
# Hidden Tests here
###
### AUTOGRADER TEST - DO NOT REMOVE
###
